version: '3'
services:

  auth-db:
    image: postgres:11
    container_name: auth-db  
    restart: always
    networks:
        - sales-network
    environment:
      - POSTGRES_DB=auth-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234567
    ports: 
      - 5432:5432

  product-db:
    image: postgres:11
    container_name: product-db
    restart: always
    networks:
        - sales-network
    environment:  
      - POSTGRES_DB=product-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234567
    ports: 
      - 5433:5432

  sales-db:
    image: mongodb/mongodb-community-server:latest
    container_name: sales-db
    restart: always
    networks:
        - sales-network
    environment:  
      - MONGODB_DATABASE=sales-db
      - MONGODB_USER=admin
      - MONGODB_PASSWORD=123456
    ports: 
      - 27017:27017

  auth-api:
      build: './auth-api'
      container_name: auth-api 
      depends_on:
        - auth-db
      networks:
        - sales-network
      environment:
        - PORT=8080
        - API_SECRET=YXV0aC1hcGktc2VjcmV0LWNvbnRhaW5lci0yMDI0
        - DB_HOST=auth-db
        - DB_NAME=auth-db
        - DB_USER=admin
        - DB_PASSWORD=1234567
        - DB_PORT=5432
      ports: 
        - 8080:8080

  product-api:
      build: './product-api'
      container_name: product-api
      depends_on:
        - product-db
        - rabbit
      networks:
        - sales-network
      environment:
        - PORT=8081
        - API_SECRET=YXV0aC1hcGktc2VjcmV0LWNvbnRhaW5lci0yMDI0
        - DB_HOST=product-db
        - DB_NAME=product-db
        - DB_USER=admin
        - DB_PASSWORD=1234567
        - DB_PORT=5432
        - RABBIT_MQ_HOST=rabbit
        - RABBIT_MQ_PORT=5672
        - RABBIT_MQ_USERNAME=guest
        - RABBIT_MQ_PASSWORD=guest
        - SALES_HOST=sales-api
        - SALES_PORT=8082
        - NODE_ENV=container
      ports: 
        - 8081:8081

  sales-api:
      build: './sales-api'
      container_name: sales-api  
      depends_on:
        - product-db
        - rabbit
      networks:
        - sales-network
      environment:
        - PORT=8082
        - API_SECRET=YXV0aC1hcGktc2VjcmV0LWNvbnRhaW5lci0yMDI0
        - MONGO_DB_URL=mongodb://admin:123456@sales-db:27017/sales-db
        - RABBIT_MQ_URL=amqp://rabbit:5672
        - PRODUCT_API_URL=http://localhost:8081/products
      ports: 
        - 8082:8082

  
  rabbit:
      image: rabbitmq:3-management
      container_name: sales-rabbit
      hostname:  rabbit
      restart: always
      networks:
        - sales-network
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASSWORD=guest
      ports: 
        - 5672:5672
        - 15672:15672
        - 25676:25676

networks:
  sales-network:
    drivers: bridge